-- 코드를 입력하세요
SELECT A.ID, A.NAME, A.HOST_ID FROM PLACES AS A JOIN (SELECT HOST_ID, COUNT(HOST_ID) AS COUNT FROM PLACES GROUP BY HOST_ID ORDER BY HOST_ID) AS B ON A.HOST_ID = B.HOST_ID WHERE B.COUNT >= 2 ORDER BY A.ID;
# select * from places;